name: CI
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai

    steps:
      - name: checkout themes
        run: |
          git clone https://github.com/coderqs/eureka-prsnl.git main
      
      - name: merge article repo to themes
        run: |
          git merge 

      - name: Read Hugo info
        id: hugo-info
        run: |
          . ./.HUGO_VERSION
          echo "HUGO_VERSION=${HUGO_VERSION}">> $GITHUB_OUTPUT
          echo "HUGO_EXTENDED=${HUGO_EXTENDED}">> $GITHUB_OUTPUT

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${{ steps.hugo-info.outputs.HUGO_VERSION }}' #"latest"
          extended: ${{ steps.hugo-info.outputs.HUGO_EXTENDED }} #true 

      - name: Build
        run: hugo --minify --gc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: coderqs/eureka-prsnl
          publish_dir: ./public
          #   keep_files: true
          user_name: coderqs
          user_email: <coderqs@coderqs.com>
          publish_branch: gh-pages
          cname: coderqs.com
          timezone: 'Asia/Shanghai'