name: CI
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai

    steps:
      - name: checkout themes and merge article repo to themes
        run: |
          git config --global user.email "coderqs@coderqs.com"
          git config --global user.name "coderqs"
          git clone -b main https://github.com/coderqs/eureka-prsnl.git .
          git remote add article https://github.com/coderqs/article.git
          git fetch article
          git merge --no-commit --strategy=ours  article/main --allow-unrelated-histories -m "GA auto-merge for release"
          git read-tree --prefix=content/posts/ -u article/main
          rm -rf content/posts/template
          echo --- show all ---
          ls -al  
          echo ---
          ls -al content/posts/
          echo --- show end ---

      - name: Read Hugo info
        id: hugo-info
        run: |
          . ./.HUGO_VERSION
          echo "HUGO_VERSION=${HUGO_VERSION}">> $GITHUB_OUTPUT
          echo "HUGO_EXTENDED=${HUGO_EXTENDED}">> $GITHUB_OUTPUT

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${{ steps.hugo-info.outputs.HUGO_VERSION }}' #"latest"
          extended: ${{ steps.hugo-info.outputs.HUGO_EXTENDED }} #true 

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # The action defaults to search for the dependency file (package-lock.json,
          # npm-shrinkwrap.json or yarn.lock) in the repository root, and uses its
          # hash as a part of the cache key.
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache-dependency-path: '**/package-lock.json'
      - run: |
          cp themes/hugo-eureka/package*.json .
          npm ci
          echo --- hugo version ---
          hugo version
          echo --- end ---
          hugo --minify --gc
          echo --- show all file ---
          ls -al 
          echo ---
          ls -al public
          echo --- end ---

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: coderqs/eureka-prsnl
          publish_dir: ./public
          #   keep_files: true
          user_name: coderqs
          user_email: <coderqs@coderqs.com>
          publish_branch: gh-pages
          cname: blog.coderqs.com